[build]
  base = "aigents-web"
  command = "npm install && npm run build"
  publish = "out"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"
